services:
  demonopedia-backend:
    image: node:latest
    container_name: demonopedia-backend
    ports:
      - "6002:6002"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"